version: '3.4'

services:
  catalogdb:
    container_name:  catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db" 
       
  basketdb:
    container_name:  basketdb
    restart: always
    ports:
      - "6379:6379"

  pontainer:
    container_name:  pontainer
    restart: always
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - pontainer_data:/data

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"


  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSetting:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"

